### ISSUE TITLE
As in the previous versions, the following error occurs:

### ISSUE THREAD

**Issue by carsteneu** [PapooSoftware/PapooCMS#2]
If an article is to be listed (teased) on the home page and a value other than 0 is entered in the from-date (the to-date is in the future), the article is not displayed on the home page.

Only if the to-date is 0, the article will be listed on the start page.

**Comment by cz-papoo** [comment]
This is an old bug that was already fixed on April 14, 2021. Unfortunately, the corresponding commit was lost when the project was moved to GitHub.

Anyhow, I can't reproduce the described behavior any longer in the current version.
