### ISSUE TITLE
Installation - Step 4

### ISSUE THREAD

**Issue by martok12** [PapooSoftware/PapooCMS#5]
During the installation of  papoo cms , the site -step 4- appears (databes tables were registered) and thats it - no step 5 is comming.
Any suggestions?

![Schritt 4](https://user-images.githubusercontent.com/88455430/128234616-e1f77b95-21c1-4484-aa87-1c1158bf3ed5.PNG)

**Comment by cz-papoo** [comment]
This seems to be a problem related to PHP 8.0, a fix has been provided with b286e64.

Please pull the latest commit of the main branch and try again.
