### ISSUE TITLE
Search of subscribers in the Newsletter-Plugin is broken

### ISSUE THREAD

**Issue by ah-papoo** [PapooSoftware/PapooCMS#7]
Search of subscribers in the Newsletter-Plugin is not working as expected, when not selecting a list of a subscriber-list.
This used to work at some point but not anymore.

**Comment by bebogen** [comment]
have the same problem, is there no answer?

**Comment by ah-papoo** [comment]
> have the same problem, is there no answer?

This is an issue-tracker, when someone gets to fixing this issue, there will be a reply and the issue will be closed.

**Comment by cz-papoo** [comment]
I was able to produce an error where no results were listed if no mailing list had been specified in a search and the missing subscribers weren't assigned a mailing list either. Is this the error both of you are experiencing?

Anyhow, a fix for this issue has been provided with 8f68d0b.

Please pull the latest commit of the main branch and try again.
